## Numpy 

## Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#evenly space in between numbers
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5,3)

array([[0.20060234, 0.66722691, 0.52136981],
       [0.81875028, 0.16865332, 0.42514456],
       [0.15441398, 0.30009064, 0.81969903],
       [0.55564711, 0.38411755, 0.62715127],
       [0.95618608, 0.29247935, 0.26642075]])

In [17]:
np.random.randn(10)

array([ 0.38688543,  1.23660722,  0.65125833, -0.70218843, -0.72759017,
        0.78626137,  0.66700309, -0.2750135 , -1.75640866,  0.1866986 ])

In [18]:
np.random.randn(2,3)

array([[-0.17947743, -0.08315854,  0.15336342],
       [-0.88218303, -0.86708738,  0.95319034]])

In [19]:
np.random.randint(0,101,(4,5))

array([[19, 21, 90, 28, 97],
       [ 7, 80,  5, 28, 36],
       [82, 24, 58, 71,  3],
       [ 1, 44, 64, 28, 12]])

In [20]:
np.random.randint(0,101,10)

array([60, 75,  0, 20, 85, 30,  8, 70, 74, 46])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr = np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [25]:
ranarr.max()

99

In [26]:
ranarr.min()

2

In [27]:
ranarr.argmax()

5

In [28]:
ranarr.argmin()

7

In [29]:
ranarr.dtype

dtype('int32')

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.shape

(25,)

In [32]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [33]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Indexing and Selection

In [34]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[8]

8

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#Broadcasting
arr[0:5] = 100

In [41]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr = np.arange(0,11)

In [43]:
slice_of_arr = arr[0:5]

In [44]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr[:] = 99

In [47]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [49]:
arr_copy = arr.copy()

In [50]:
arr_copy[:] = 100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d.shape

(3, 3)

In [57]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[0,2]

15

In [63]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [64]:
#Conditional Selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
bool_arr = arr > 4

In [67]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [71]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [74]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [77]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
arr / arr

C:\Users\epcus\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
1 / 0

ZeroDivisionError: division by zero

In [80]:
1 / arr

C:\Users\epcus\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [81]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [83]:
np.log(arr)

C:\Users\epcus\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
arr.sum()

45

In [85]:
arr.mean()

4.5

In [86]:
arr.max()

9

In [87]:
arr.var()

8.25

In [88]:
arr.std()

2.8722813232690143

In [90]:
arr2d = np.arange(0,25).reshape(5,5)

In [91]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr2d.sum()

300

In [93]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [94]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])